import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  ArrowClockwise,
  ArrowsLeftRight,
  BookOpenText,
  CaretDown,
  CaretRight,
  CaretUp,
  ChartBar,
  Check,
  Circle,
  ClipboardText,
  CloudArrowDown,
  Code,
  Copy,
  Database,
  DownloadSimple,
  Export,
  Eye,
  FileMagnifyingGlass,
  Gear,
  Globe,
  HandsClapping,
  Info,
  Keyboard,
  Link,
  LockKey,
  MagnifyingGlass,
  Network,
  PaintBrush,
  PaperPlaneTilt,
  Plus,
  Power,
  PushPin,
  PuzzlePiece,
  SlidersHorizontal,
  Sparkle,
  Speedometer,
  SquaresFour,
  Textbox,
  Trash,
  Tray,
  Warning,
  Waveform,
  Wrench,
  X,
} from "@phosphor-icons/react";

const icons = {
  refresh: ArrowClockwise,
  swap: ArrowsLeftRight,
  book: BookOpenText,
  down: CaretDown,
  right: CaretRight,
  up: CaretUp,
  chart: ChartBar,
  check: Check,
  circle: Circle,
  clipboard: ClipboardText,
  cloudDownload: CloudArrowDown,
  code: Code,
  copy: Copy,
  database: Database,
  download: DownloadSimple,
  export: Export,
  eye: Eye,
  fileSearch: FileMagnifyingGlass,
  gear: Gear,
  globe: Globe,
  hands: HandsClapping,
  info: Info,
  keyboard: Keyboard,
  link: Link,
  lock: LockKey,
  search: MagnifyingGlass,
  network: Network,
  appearance: PaintBrush,
  send: PaperPlaneTilt,
  plus: Plus,
  power: Power,
  pin: PushPin,
  plugin: PuzzlePiece,
  sliders: SlidersHorizontal,
  sparkle: Sparkle,
  speed: Speedometer,
  grid: SquaresFour,
  textbox: Textbox,
  trash: Trash,
  tray: Tray,
  warning: Warning,
  waveform: Waveform,
  tools: Wrench,
  close: X,
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  size = 18,
  weight = "regular",
  className,
}: {
  name: IconName;
  size?: number;
  weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone";
  className?: string;
}) {
  const Component = icons[name];
  return <Component aria-hidden="true" className={className} size={size} weight={weight} />;
}
