// Generated by scripts/sync-buffer-plugin-catalog.py from
// Catalog/buffer-plugins.json. Do not edit this file directly.

enum PresetBufferPluginCatalog {
    static let entries: [PresetBufferPluginCatalogEntry] = [
        PresetBufferPluginCatalogEntry(
            id: "builtin.ai-text",
            nameZH: "AI 生成",
            nameEN: "AI Generation",
            version: "2.0",
            summaryZH: "使用设置中选定的 Codex、Claude Code 或通用 Open API（OpenAI 兼容）连接器生成独立目标缓冲区。",
            summaryEN: "Generate an independent target buffer with the selected Codex, Claude Code, or OpenAI-compatible connector.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.my-prompt",
            nameZH: "My Prompt",
            nameEN: "My Prompt",
            version: "1.0",
            summaryZH: "从本地 Markdown、Obsidian 或 Fabric 风格提示词库实时检索；远程 Git 仓库先同步到本地索引。",
            summaryEN: "Search local Markdown, Obsidian, or Fabric-style prompt libraries, with remote Git repositories synchronized into the local index first.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.apple-translation",
            nameZH: "实时翻译",
            nameEN: "Real-time Translation",
            version: "2.0",
            summaryZH: "把源缓冲区实时翻译到独立目标缓冲区；默认使用 Apple 本地翻译，也可选择当前 AI 渠道。",
            summaryEN: "Translate the source buffer into an independent target buffer with Apple on-device translation by default or the current AI connector.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.stream-input",
            nameZH: "意识流输入",
            nameEN: "Stream of Consciousness Input",
            version: "1.2",
            summaryZH: "连续输入不分词的全拼，按单独配置的 AI 渠道、1–5 个候选上限和响应节奏实时给出完整猜测。",
            summaryEN: "Continuously interpret unsegmented full Pinyin with an independent AI connector, a one-to-five candidate limit, and a configurable response pace.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.remarkable",
            nameZH: "Remarkable",
            nameEN: "Remarkable",
            version: "2.0",
            summaryZH: "只读导出 reMarkable 当前页，并用 Apple Vision 在 Mac 本地识别；结果先进入缓冲区供核对。",
            summaryEN: "Read the current reMarkable page over USB and recognize it locally with Apple Vision before staging the result for review.",
            defaultInstalled: false,
            defaultEnabled: false,
            downloadAssetName: "preset-plugin-builtin.remarkable-2.0.json",
            sha256: "4d1d19158f1ee06dc0a556ea599e1a97b9630805a8e17612a192d2b9113a3893"
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.marine-chrome",
            nameZH: "Marine Chrome",
            nameEN: "Marine Chrome",
            version: "0.2.3",
            summaryZH: "由配套 Chrome 扩展读取当前网页和精确回复目标；生成与发送仍由 RIMES 安全处理。",
            summaryEN: "Use the companion Chrome extension to read the current page and exact reply target while RIMES retains generation and delivery control.",
            defaultInstalled: false,
            defaultEnabled: false,
            downloadAssetName: "preset-plugin-builtin.marine-chrome-0.2.3.json",
            sha256: "9b0f797fe02ff95e4ce976a40543f80552e5039e2c9f3095941e72433795f05d"
        ),
    ]

    static func entry(id: String) -> PresetBufferPluginCatalogEntry? {
        entries.first { $0.id == id }
    }
}
