// Generated by scripts/sync-buffer-plugin-catalog.py from
// Catalog/buffer-plugins.json. Do not edit this file directly.

enum PresetBufferPluginCatalog {
    static let entries: [PresetBufferPluginCatalogEntry] = [
        PresetBufferPluginCatalogEntry(
            id: "builtin.ai-text",
            nameZH: "AI 生成",
            nameEN: "AI Generation",
            version: "2.1",
            summaryZH: "使用设置中选定的 Codex、Claude Code 或通用 Open API（OpenAI 兼容）连接器生成独立目标缓冲区。",
            summaryEN: "Generate an independent target buffer with the selected Codex, Claude Code, or OpenAI-compatible connector.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.apple-translation",
            nameZH: "实时翻译",
            nameEN: "Real-time Translation",
            version: "2.1",
            summaryZH: "把源缓冲区实时翻译到独立目标缓冲区；默认使用 Apple 本地翻译，也可选择当前 AI 渠道。",
            summaryEN: "Translate the source buffer into an independent target buffer with Apple on-device translation by default or the current AI connector.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.stream-input",
            nameZH: "意识流输入",
            nameEN: "Stream of Consciousness Input",
            version: "1.4",
            summaryZH: "连续输入全拼，由本地 Rime + Octagram 模块低延迟解码，复杂输入再回退到独立 AI 渠道，并给出 1–5 个完整候选。",
            summaryEN: "Decode continuous full Pinyin with a low-latency local Rime + Octagram module, falling back to the independent AI connector for complex input and returning one to five complete guesses.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
        PresetBufferPluginCatalogEntry(
            id: "builtin.music",
            nameZH: "电音演奏",
            nameEN: "Electronic Music",
            version: "0.2.3",
            summaryZH: "用 AudioKit 演奏四弦贝斯排列的 40 键电音，搭配真实采样架子鼓、八种加花和两轨 Loop；演奏键仅在音乐面板获焦时生效。",
            summaryEN: "Play 40 electronic notes in a four-string bass layout with AudioKit, a sampled acoustic drum kit, eight fills and two loop tracks. Performance keys are scoped to the focused music panel.",
            defaultInstalled: true,
            defaultEnabled: true,
            downloadAssetName: nil,
            sha256: nil
        ),
    ]

    static func entry(id: String) -> PresetBufferPluginCatalogEntry? {
        entries.first { $0.id == id }
    }
}
